version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: gomod
    directories:
      - .sage
      - /
      - cmd/monta
    multi-ecosystem-group: "all-dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      exclude:
        - github.com/einride/*
        - github.com/einride-autonomous/*
        - github.com/einride-labs/*
